### PR TITLE
feat(upgrade): Update to mary protocol version

### PR DESCRIPTION
**Pull request by mark-stopka**
@pavlix this looks like a issue-less merge, what do you think?

### CODE REVIEW

**Comment by mark-stopka** [comment]
@pavlix, @AndrewWestberg build is failing....

**Comment by pavlix** [comment]
@AndrewWestberg Your modifications expect only Mary to be used. Is that intended?

**Review by pavlix — COMMENTED** [review]
If the Mary is intended to be the only allowed protocol now, we're good. Otherwise, the min protocol should be changed back.

**Comment by mark-stopka** [comment]
I think the minimal version of the proto ol should come from the crate consumer, not from the library itself, what do you think @AndrewWestberg?

**Pull request merged**
