### PR TITLE
refactor: handshake protocol refactoring

### PR DESCRIPTION
**Pull request by pavlix**
Proper client and server logic. The API is tentative and may slightly change before the next release.

### CODE REVIEW

**Comment by pavlix** [comment]
@AndrewWestberg I humbly ask not only for review of the particular changes in this request but also the whole idea of how the library would be used as of the next version. Some of the changes were merged already to get us on track but this is the best time to collect feedback and adjust the modifications accordingly.

Tokio is now a hard dependency that can be lifted later. Some of the features are not yet on par with the last version but most are far better now and more is to come.

**Comment by mark-stopka** [comment]
@pavlix conflicts here need to either be resolved, or the PR dismissed, I am not sure if it is still needed...

**Comment by pavlix** [comment]
> @pavlix conflicts here need to either be resolved, or the PR dismissed, I am not sure if it is still needed...

It is still active and important.

**Comment by mark-stopka** [comment]
@pavlix please resolve conflicts so that we can merge to master.

**Pull request merged**
